# Generated by Django 5.2.15 on 2026-06-08 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField(blank=True, help_text='¿Cómo te ves en el futuro?', null=True)),
                ('mission', models.TextField(blank=True, help_text='¿Qué vas a hacer para lograrlo?', null=True)),
                ('target_profession', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('grado', models.CharField(help_text='10° u 11°', max_length=20)),
                ('curso', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('term', models.CharField(choices=[('SHORT', 'Corto Plazo'), ('MEDIUM', 'Mediano Plazo'), ('LONG', 'Largo Plazo')], default='SHORT', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='assessments.lifeproject')),
            ],
        ),
        migrations.AddField(
            model_name='lifeproject',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='life_project', to='assessments.student'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(default=list, help_text='Lista de respuestas del estudiante')),
                ('resultados_por_area', models.JSONField(default=dict, help_text='Estructura similar a resultados_acumulados.json')),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('COMPLETADO', 'Completado')], default='COMPLETADO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.student')),
            ],
        ),
    ]
